// ---------------------------------------------------------------------------------------------------------------------
// This is the configuration file for building the Obsidian plugin.
// ---------------------------------------------------------------------------------------------------------------------
import esbuild from 'esbuild';
import { sassPlugin } from 'esbuild-sass-plugin';
import process from 'process';

import { external, outdir } from './build.config.mjs';
import esbuildObsidian from './esbuild-plugin-obsidian.mjs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts', 'src/styles.scss'],
	bundle: true,
	plugins: [sassPlugin({ type: 'css' }), esbuildObsidian({ manifestFile: `${outdir}/manifest.json` })],
	format: 'cjs',
	target: 'es2018',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	external,
	outdir,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
